# helm install --values values.yaml --name nginx-ingress stable/nginx-ingress
controller:
  service:
    type: NodePort
  kind: DaemonSet
  daemonset:
    useHostPort: true
  resources:
    requests:
      cpu: 25m
rbac:
  create: true