// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/cube2222/usos-notifier/credentials/credentials.proto

/*
Package credentials is a generated protocol buffer package.

It is generated from these files:
	github.com/cube2222/usos-notifier/credentials/credentials.proto

It has these top-level messages:
	GetSessionRequest
	GetSessionResponse
*/
package credentials

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type GetSessionRequest struct {
	Userid string `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *GetSessionRequest) Reset()                    { *m = GetSessionRequest{} }
func (m *GetSessionRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSessionRequest) ProtoMessage()               {}
func (*GetSessionRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *GetSessionRequest) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type GetSessionResponse struct {
	Sessionid string `protobuf:"bytes,1,opt,name=sessionid" json:"sessionid,omitempty"`
}

func (m *GetSessionResponse) Reset()                    { *m = GetSessionResponse{} }
func (m *GetSessionResponse) String() string            { return proto.CompactTextString(m) }
func (*GetSessionResponse) ProtoMessage()               {}
func (*GetSessionResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *GetSessionResponse) GetSessionid() string {
	if m != nil {
		return m.Sessionid
	}
	return ""
}

func init() {
	proto.RegisterType((*GetSessionRequest)(nil), "credentials.GetSessionRequest")
	proto.RegisterType((*GetSessionResponse)(nil), "credentials.GetSessionResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Credentials service

type CredentialsClient interface {
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
}

type credentialsClient struct {
	cc *grpc.ClientConn
}

func NewCredentialsClient(cc *grpc.ClientConn) CredentialsClient {
	return &credentialsClient{cc}
}

func (c *credentialsClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	out := new(GetSessionResponse)
	err := grpc.Invoke(ctx, "/credentials.Credentials/GetSession", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Credentials service

type CredentialsServer interface {
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
}

func RegisterCredentialsServer(s *grpc.Server, srv CredentialsServer) {
	s.RegisterService(&_Credentials_serviceDesc, srv)
}

func _Credentials_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CredentialsServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/credentials.Credentials/GetSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CredentialsServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Credentials_serviceDesc = grpc.ServiceDesc{
	ServiceName: "credentials.Credentials",
	HandlerType: (*CredentialsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSession",
			Handler:    _Credentials_GetSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/cube2222/usos-notifier/credentials/credentials.proto",
}

func init() {
	proto.RegisterFile("github.com/cube2222/usos-notifier/credentials/credentials.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 185 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x4f, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2e, 0x4d, 0x4a, 0x35, 0x32, 0x32, 0x32, 0xd2,
	0x2f, 0x2d, 0xce, 0x2f, 0xd6, 0xcd, 0xcb, 0x2f, 0xc9, 0x4c, 0xcb, 0x4c, 0x2d, 0xd2, 0x4f, 0x2e,
	0x4a, 0x4d, 0x49, 0xcd, 0x2b, 0xc9, 0x4c, 0xcc, 0x29, 0x46, 0x66, 0xeb, 0x15, 0x14, 0xe5, 0x97,
	0xe4, 0x0b, 0x71, 0x23, 0x09, 0x29, 0x69, 0x73, 0x09, 0xba, 0xa7, 0x96, 0x04, 0xa7, 0x16, 0x17,
	0x67, 0xe6, 0xe7, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0x89, 0x71, 0xb1, 0x95, 0x16,
	0xa7, 0x16, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x70, 0x06, 0x41, 0x79, 0x4a, 0x46, 0x5c,
	0x42, 0xc8, 0x8a, 0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x85, 0x64, 0xb8, 0x38, 0x8b, 0x21, 0x42,
	0x70, 0x0d, 0x08, 0x01, 0xa3, 0x18, 0x2e, 0x6e, 0x67, 0x84, 0x7d, 0x42, 0xbe, 0x5c, 0x5c, 0x08,
	0x23, 0x84, 0xe4, 0xf4, 0x90, 0x9d, 0x87, 0xe1, 0x10, 0x29, 0x79, 0x9c, 0xf2, 0x10, 0xbb, 0x9d,
	0xf4, 0xa3, 0x74, 0x49, 0x0a, 0x8e, 0x24, 0x36, 0x70, 0x18, 0x18, 0x03, 0x02, 0x00, 0x00, 0xff,
	0xff, 0xee, 0xbf, 0xc8, 0xb0, 0x46, 0x01, 0x00, 0x00,
}
