apiVersion: apps/v1
kind: Deployment
metadata:
  name: credentials
  labels:
    service: credentials
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      service: credentials
  template:
    metadata:
      labels:
        service: credentials
    spec:
      volumes:
      - name: service-account-file
        secret:
          secretName: credentials-service-account
      containers:
      - name: credentials
        image: cube2222/credentials:0.0.16
        ports:
        - containerPort: 8080
        - containerPort: 8081
        - containerPort: 6666
        resources:
          requests:
            cpu: 25m
        volumeMounts:
        - name: service-account-file
          mountPath: /var/secrets/google
        env:
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /var/secrets/google/serviceaccount.json
---
apiVersion: v1
kind: Service
metadata:
  name: credentials
  labels:
    service: credentials
spec:
  selector:
    service: credentials
  ports:
  - protocol: TCP
    port: 8080
    name: http
  - protocol: TCP
    port: 8081
    name: grpc